package install

import (
	"encoding/json"
	"fmt"
	"io/fs"
)

// renderOpenCode writes the .opencode/plugin shim pointing at the consumer
// binary (§8). The generated file is self-contained with the command baked
// in, so projects need no npm install step.
func renderOpenCode(m Manifest, _ Target) (fs.FS, error) {
	cmd, err := json.Marshal(m.Command)
	if err != nil {
		return nil, err
	}
	shim := fmt.Sprintf(openCodeShimTemplate, string(cmd))
	return memFS(map[string][]byte{
		".opencode/plugin/agenthooks.ts": []byte(shim),
	}), nil
}

// The shim speaks both plugin APIs: OpenCode 2 calls setup(), OpenCode 1
// calls server(). The V2 path emits V1-shaped frames so serve mode is unchanged.
const openCodeShimTemplate = `// Generated by agenthooks install — do not edit.
// Proxies OpenCode plugin hooks to the consumer binary over NDJSON stdio
// (agenthooks serve --provider=opencode). See DESIGN.md §8.
import { spawn, type ChildProcess } from "node:child_process"
import { createInterface } from "node:readline"

const COMMAND: string[] = %s
const HOOK_TIMEOUT_MS = 30_000

const connect = () => {
  const child: ChildProcess = spawn(COMMAND[0], [...COMMAND.slice(1), "agenthooks", "serve", "--provider=opencode"], {
    stdio: ["pipe", "pipe", "inherit"],
  })
  let seq = 0
  const pending = new Map<number, (v: any) => void>()

  createInterface({ input: child.stdout! }).on("line", (line) => {
    if (!line.trim()) return
    let reply: any
    try {
      reply = JSON.parse(line)
    } catch {
      return
    }
    const resolve = pending.get(reply.seq)
    if (!resolve) return
    pending.delete(reply.seq)
    resolve(reply)
  })
  child.on("exit", () => {
    for (const [, resolve] of pending) resolve({})
    pending.clear()
  })

  const call = (hook: string, input: unknown, output: unknown): Promise<any> => {
    if (child.exitCode !== null || !child.stdin?.writable) return Promise.resolve({})
    const id = ++seq
    child.stdin.write(JSON.stringify({ seq: id, hook, input, output }) + "\n")
    return new Promise((resolve) => {
      pending.set(id, resolve)
      // The shim adds the timeout policy OpenCode lacks.
      const timer = setTimeout(() => {
        if (pending.delete(id)) resolve({})
      }, HOOK_TIMEOUT_MS)
      // Don't keep the event loop alive for a hook reply.
      if (typeof timer.unref === "function") timer.unref()
    })
  }

  const close = () => {
    try {
      child.stdin!.end()
      child.kill()
    } catch {}
  }

  return { call, close }
}

const apply = (target: any, reply: any) => {
  if (reply?.error) throw new Error(reply.error)
  if (reply?.output && target && typeof target === "object") {
    // Arrays replaced wholesale, preserving OpenCode's mutation semantics.
    Object.assign(target, reply.output)
  }
}

const sum = (a: any, b: any) => (typeof b === "number" ? (a ?? 0) + b : a)

// Stop usage is the turn's total across every step.
const addUsage = (acc: any, step: any) => ({
  cost: sum(acc?.cost, step?.cost),
  tokens: {
    input: sum(acc?.tokens?.input, step?.tokens?.input),
    output: sum(acc?.tokens?.output, step?.tokens?.output),
    reasoning: sum(acc?.tokens?.reasoning, step?.tokens?.reasoning),
    cache: {
      read: sum(acc?.tokens?.cache?.read, step?.tokens?.cache?.read),
      write: sum(acc?.tokens?.cache?.write, step?.tokens?.cache?.write),
    },
  },
})

const legacy = async (ctx: any) => {
  const { call, close } = connect()
  const failedCalls = new Set<string>()

  let initialized: Promise<void> | undefined
  const initialize = () => initialized ??= (async () => {
    let mcp: Record<string, unknown> | undefined
    try {
      const config: any = (await ctx.client.config.get())?.data
      if (config) {
        mcp = {}
        for (const [name, server] of Object.entries(config.mcp ?? {}) as [string, any][]) {
          mcp[name] = {
            type: server?.type,
            command: server?.command,
            url: server?.url,
            enabled: server?.enabled,
          }
        }
      }
    } catch {}
    await call("initialize", {
      serverUrl: ctx?.serverUrl ?? ctx?.client?.baseUrl ?? "",
      directory: ctx?.directory ?? "",
      worktree: ctx?.worktree ?? "",
      ...(mcp === undefined ? {} : { mcp }),
    }, null)
  })()

  const forward = (hook: string) => async (input: unknown, output: unknown) => {
    await initialize()
    apply(output, await call(hook, input, output))
  }

  return {
    "chat.message": forward("chat.message"),
    "chat.params": forward("chat.params"),
    "tool.execute.before": forward("tool.execute.before"),
    "tool.execute.after": forward("tool.execute.after"),
    event: async ({ event }: any) => {
      let input = event?.properties ?? {}
      if (event?.type === "message.part.updated") {
        const part = input?.part
        // Only failed tool parts are reported: tool.execute.after does not
        // fire when a tool errors, and streaming deltas would flood the pipe.
        if (part?.type !== "tool" || part?.state?.status !== "error") return
        if (failedCalls.has(part.callID)) return
        failedCalls.add(part.callID)
      }
      const ready = initialize()
      // No native hook or bus event carries the completed assistant text, so
      // splice the transcript's final assistant message into the stop event
      // the way Claude/Codex report last_assistant_message.
      if (event?.type === "session.idle" && input?.sessionID) {
        try {
          const res: any = await ctx.client.session.messages({ path: { id: input.sessionID } })
          const msgs: any[] = res?.data ?? []
          for (let i = msgs.length - 1; i >= 0; i--) {
            const m = msgs[i]
            if (m?.info?.role !== "assistant") continue
            const text = (m.parts ?? [])
              .filter((p: any) => p?.type === "text" && p.text && !p.synthetic)
              .map((p: any) => p.text)
              .join("\n")
            if (text) input = { ...input, finalMessage: text }
            // No native hook carries end-of-turn totals either; lift the same
            // message's info.tokens / info.cost into the stop event.
            const info: any = m?.info ?? {}
            if (info.tokens || info.cost != null) {
              input = { ...input, usage: { tokens: info.tokens, cost: info.cost } }
            }
            break
          }
        } catch {}
      }
      await ready
      apply(null, await call(event?.type ?? "event", input, null))
    },
    dispose: close,
  }
}

const setup = async (ctx: any) => {
  const { call, close } = connect()
  const directory: string = ctx.location?.directory ?? ""
  // Bus events are service-wide; only sessions seen in this location are reported.
  const own = new Set<string>()
  const announced = new Set<string>()
  const injected = new Map<string, string>()
  const finalText = new Map<string, { id: string; texts: string[] }>()
  const usage = new Map<string, any>()

  let inventory: Record<string, unknown> | undefined
  await ctx.mcp.transform((editor: any) => {
    const snapshot: Record<string, unknown> = {}
    for (const [name, s] of editor.list() as [string, any][]) {
      snapshot[name] = { type: s?.type, command: s?.command, url: s?.url, enabled: !s?.disabled }
    }
    inventory = snapshot
  })

  let initialized: Promise<void> | undefined
  const initialize = () => initialized ??= (async () => {
    let mcp: Record<string, unknown> | undefined
    try {
      // The snapshot only sees transforms that ran before ours; send it only when complete.
      const listed: any[] = (await ctx.mcp.list())?.data ?? []
      if (inventory && listed.every((s) => s?.name in inventory!)) {
        mcp = Object.fromEntries(listed.map((s) => [s.name, inventory![s.name]]))
      }
    } catch {}
    await call("initialize", {
      serverUrl: "",
      directory,
      worktree: ctx.location?.project?.directory ?? "",
      ...(mcp === undefined ? {} : { mcp }),
    }, null)
  })()

  const send = async (hook: string, input: unknown, output: unknown) => {
    await initialize()
    const reply = await call(hook, input, output)
    if (reply?.error) throw new Error(reply.error)
    return reply?.output
  }

  const announce = async (sid: string, parentID?: string) => {
    if (announced.has(sid)) return
    announced.add(sid)
    await send("session.created", { info: { id: sid, parentID, directory } }, null)
  }

  await ctx.session.hook("prompt", async (ev: any) => {
    if (!own.has(ev.sessionID)) {
      own.add(ev.sessionID)
      // A location's first session can be created before we subscribe; no usage yet means it is new, not resumed.
      try {
        const s: any = await ctx.session.get({ sessionID: ev.sessionID })
        const t = s?.tokens
        if (t && !(t.input || t.output || t.cache?.read || t.cache?.write)) await announce(ev.sessionID, s?.parentID)
      } catch {}
    }
    injected.delete(ev.sessionID)
    finalText.delete(ev.sessionID)
    usage.delete(ev.sessionID)
    const parts = [{ type: "text", text: ev.prompt?.text ?? "" }]
    const out = await send("chat.message",
      { sessionID: ev.sessionID, messageID: ev.messageID },
      { message: { id: ev.messageID, sessionID: ev.sessionID }, parts })
    const extra = ((out?.parts ?? []) as any[]).slice(parts.length)
      .filter((p) => p?.type === "text" && p.text)
      .map((p) => p.text)
    if (extra.length) injected.set(ev.sessionID, extra.join("\n"))
  })

  await ctx.session.hook("context", async (ev: any) => {
    const extra = injected.get(ev.sessionID)
    if (extra) ev.system.push({ type: "text", text: extra })
    await send("chat.params", { sessionID: ev.sessionID, agent: ev.agent, model: ev.model }, { options: ev.options })
  })

  await ctx.tool.hook("execute.before", async (ev: any) => {
    own.add(ev.sessionID)
    const out = await send("tool.execute.before",
      { tool: ev.tool, sessionID: ev.sessionID, callID: ev.id },
      { args: ev.input })
    if (out && "args" in out) ev.input = out.args
  })

  await ctx.tool.hook("execute.after", async (ev: any) => {
    if (ev.status === "error") {
      // V1 reported failures as a tool part; keep that frame so they decode as tool errors.
      await send("message.part.updated", {
        part: {
          type: "tool", sessionID: ev.sessionID, callID: ev.id, tool: ev.tool,
          state: { status: "error", error: ev.error?.message ?? "", input: ev.input },
        },
      }, null)
      return
    }
    const content: any[] = ev.result?.content ?? []
    const text = content.filter((c) => c?.type === "text").map((c) => c.text).join("\n")
    const out = await send("tool.execute.after",
      { tool: ev.tool, sessionID: ev.sessionID, callID: ev.id },
      { args: ev.input, output: text, metadata: ev.result?.metadata })
    if (out && "output" in out) ev.result = { ...ev.result, content: [{ type: "text", text: String(out.output) }] }
  })

  const onEvent = async (ev: any) => {
    const d = ev?.data ?? {}
    const sid: string | undefined = d.sessionID
    const here = ev?.location?.directory === directory
    switch (ev?.type) {
      case "session.created":
        if (!here || !sid) return
        own.add(sid)
        return announce(sid, d.parentID)
      case "session.text.ended": {
        if (!sid || !own.has(sid)) return
        const cur = finalText.get(sid)
        if (cur?.id === d.assistantMessageID) cur.texts.push(d.text)
        else finalText.set(sid, { id: d.assistantMessageID, texts: [d.text] })
        return
      }
      case "session.step.ended":
        if (sid && own.has(sid)) usage.set(sid, addUsage(usage.get(sid), d))
        return
      case "session.deleted":
        if (!sid) return
        own.delete(sid)
        announced.delete(sid)
        injected.delete(sid)
        finalText.delete(sid)
        usage.delete(sid)
        return
      case "session.execution.succeeded":
      case "session.execution.failed":
      case "session.execution.interrupted": {
        if (!sid || !own.has(sid)) return
        const text = finalText.get(sid)?.texts.filter(Boolean).join("\n")
        const u = usage.get(sid)
        finalText.delete(sid)
        usage.delete(sid)
        return send("session.idle", {
          sessionID: sid,
          ...(text ? { finalMessage: text } : {}),
          ...(u ? { usage: u } : {}),
        }, null)
      }
      case "session.compacted":
      case "permission.asked":
        if (sid && own.has(sid)) return send(ev.type, d, null)
        return
      case "file.edited":
      case "tui.toast.show":
        if (here) return send(ev.type, d, null)
        return
      case "location.shutdown":
        if (here) return send("server.instance.disposed", { directory }, null)
        return
    }
  }

  const abort = new AbortController()
  void (async () => {
    try {
      for await (const ev of ctx.event.subscribe({ signal: abort.signal })) {
        try {
          await onEvent(ev)
        } catch {}
      }
    } catch {}
  })()

  return () => {
    abort.abort()
    close()
  }
}

// A named export would load as a second V1 plugin; keep the default only.
export default { id: "agenthooks", setup, server: legacy }
`
