package install

import (
	"encoding/json"
	"fmt"
	"io/fs"
)

// renderOpenCode writes the .opencode/plugin shim pointing at the consumer
// binary (§8). The generated file is self-contained with the command baked
// in, so projects need no npm install step.
func renderOpenCode(m Manifest, _ Target) (fs.FS, error) {
	cmd, err := json.Marshal(m.Command)
	if err != nil {
		return nil, err
	}
	shim := fmt.Sprintf(openCodeShimTemplate, string(cmd))
	return memFS(map[string][]byte{
		".opencode/plugin/agenthooks.ts": []byte(shim),
	}), nil
}

const openCodeShimTemplate = `// Generated by agenthooks install — do not edit.
// Proxies OpenCode plugin hooks to the consumer binary over NDJSON stdio
// (agenthooks serve --provider=opencode). See DESIGN.md §8.
import { spawn, type ChildProcess } from "node:child_process"
import { createInterface } from "node:readline"

const COMMAND: string[] = %s
const HOOK_TIMEOUT_MS = 30_000

export const AgentHooks = async (ctx: any) => {
  const child: ChildProcess = spawn(COMMAND[0], [...COMMAND.slice(1), "agenthooks", "serve", "--provider=opencode"], {
    stdio: ["pipe", "pipe", "inherit"],
  })
  let seq = 0
  const pending = new Map<number, { resolve: (v: any) => void; reject: (e: Error) => void }>()

  createInterface({ input: child.stdout! }).on("line", (line) => {
    if (!line.trim()) return
    let reply: any
    try {
      reply = JSON.parse(line)
    } catch {
      return
    }
    const p = pending.get(reply.seq)
    if (!p) return
    pending.delete(reply.seq)
    p.resolve(reply)
  })
  child.on("exit", () => {
    for (const [, p] of pending) p.resolve({})
    pending.clear()
  })

  const call = (hook: string, input: unknown, output: unknown): Promise<any> => {
    if (child.exitCode !== null || !child.stdin?.writable) return Promise.resolve({})
    const id = ++seq
    child.stdin.write(JSON.stringify({ seq: id, hook, input, output }) + "\n")
    return new Promise((resolve) => {
      pending.set(id, { resolve, reject: resolve as any })
      // The shim adds the timeout policy OpenCode lacks.
      const timer = setTimeout(() => {
        if (pending.delete(id)) resolve({})
      }, HOOK_TIMEOUT_MS)
      // Don't keep the event loop alive for a hook reply.
      if (typeof timer.unref === "function") timer.unref()
    })
  }

  const apply = (target: any, reply: any) => {
    if (reply?.error) throw new Error(reply.error)
    if (reply?.output && target && typeof target === "object") {
      // Arrays replaced wholesale, preserving OpenCode's mutation semantics.
      Object.assign(target, reply.output)
    }
  }

  await call("initialize", {
    serverUrl: ctx?.serverUrl ?? ctx?.client?.baseUrl ?? "",
    directory: ctx?.directory ?? "",
    worktree: ctx?.worktree ?? "",
  }, null)

  const forward = (hook: string) => async (input: unknown, output: unknown) =>
    apply(output, await call(hook, input, output))

  return {
    "chat.message": forward("chat.message"),
    "chat.params": forward("chat.params"),
    "tool.execute.before": forward("tool.execute.before"),
    "tool.execute.after": forward("tool.execute.after"),
    event: async ({ event }: any) =>
      apply(null, await call(event?.type ?? "event", event?.properties ?? {}, null)),
    dispose: () => {
      try {
        child.stdin!.end()
        child.kill()
      } catch {}
    },
  }
}

export default AgentHooks
`
