package install

import (
	"errors"
	"fmt"
	"io/fs"
	"path"
	"strings"
	"unicode"

	"github.com/speakeasy-api/agenthooks"
)

// Moltis discovers one HOOK.md per hook directory. Tool post and error share
// AfterToolCall on the native side; grouping by native event ensures the
// consumer runs once and lets the codec choose tool.post versus tool.error
// from the payload's success field.
var kindToMoltis = map[agenthooks.EventKind]string{
	agenthooks.KindSessionStart:    "SessionStart",
	agenthooks.KindSessionEnd:      "SessionEnd",
	agenthooks.KindPromptSubmitted: "MessageReceived",
	agenthooks.KindToolPre:         "BeforeToolCall",
	agenthooks.KindToolPost:        "AfterToolCall",
	agenthooks.KindToolError:       "AfterToolCall",
	agenthooks.KindStop:            "AgentEnd",
	agenthooks.KindCompactPre:      "BeforeCompaction",
	agenthooks.KindCompactPost:     "AfterCompaction",
	agenthooks.KindModelRequest:    "BeforeLLMCall",
	agenthooks.KindModelResponse:   "AfterLLMCall",
}

var moltisEventOrder = []string{
	"SessionStart",
	"MessageReceived",
	"BeforeLLMCall",
	"AfterLLMCall",
	"BeforeToolCall",
	"AfterToolCall",
	"BeforeCompaction",
	"AfterCompaction",
	"AgentEnd",
	"SessionEnd",
}

func renderMoltis(m Manifest, t Target) (fs.FS, error) {
	if t.Scope == ScopePlugin {
		return nil, errors.New("install: moltis has no plugin hook scope; use ScopeUser or ScopeProject")
	}

	byEvent := map[string][]HookSpec{}
	for _, spec := range m.Hooks {
		event, ok := kindToMoltis[spec.Kind]
		if !ok {
			continue
		}
		byEvent[event] = append(byEvent[event], spec)
	}

	id := m.Identity.Name
	if id == "" {
		id = "agenthooks"
	}
	description := m.Identity.Description
	if description == "" {
		description = "Generated agenthooks bridge for Moltis."
	}
	root := "hooks"
	if t.Scope == ScopeProject {
		root = ".moltis/hooks"
	}

	files := map[string][]byte{}
	for _, event := range moltisEventOrder {
		specs := byEvent[event]
		if len(specs) == 0 {
			continue
		}
		combined := combineMoltisSpecs(specs)
		name := id + ":" + event
		var body strings.Builder
		body.WriteString("+++\n")
		fmt.Fprintf(&body, "name = %s\n", tomlString(name))
		fmt.Fprintf(&body, "description = %s\n", tomlString(description))
		fmt.Fprintf(&body, "events = [%s]\n", tomlString(event))
		fmt.Fprintf(&body, "command = %s\n", tomlString(hookCommand(m, agenthooks.ProviderMoltis, combined)))
		fmt.Fprintf(&body, "timeout = %d\n", timeoutSeconds(combined))
		body.WriteString("+++\n\n")
		fmt.Fprintf(&body, "# %s\n\nGenerated by agenthooks; edit the manifest, not this file.\n", name)

		dir := moltisSlug(id) + "-" + moltisSlug(event)
		files[path.Join(root, dir, "HOOK.md")] = []byte(body.String())
	}
	return memFS(files), nil
}

func combineMoltisSpecs(specs []HookSpec) HookSpec {
	combined := specs[0]
	matchAll := combined.Tools.IsEmpty()
	if matchAll {
		combined.Tools = ToolMatcher{}
	}
	for _, spec := range specs[1:] {
		combined.Blocking = combined.Blocking || spec.Blocking
		if spec.Timeout > combined.Timeout {
			combined.Timeout = spec.Timeout
		}
		// Specs sharing a native event are alternatives. One unscoped spec
		// therefore makes the union match all; retaining only the scoped names
		// would silently stop the unscoped handler from receiving other tools.
		if matchAll {
			continue
		}
		if spec.Tools.IsEmpty() {
			combined.Tools = ToolMatcher{}
			matchAll = true
			continue
		}
		combined.Tools.Names = append(combined.Tools.Names, spec.Tools.Names...)
		combined.Tools.Canonical = append(combined.Tools.Canonical, spec.Tools.Canonical...)
		combined.Tools.MCP = append(combined.Tools.MCP, spec.Tools.MCP...)
	}
	combined.Tools.Names = unique(combined.Tools.Names)
	combined.Tools.Canonical = unique(combined.Tools.Canonical)
	combined.Tools.MCP = unique(combined.Tools.MCP)
	return combined
}

func unique[T comparable](values []T) []T {
	seen := make(map[T]struct{}, len(values))
	out := make([]T, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func moltisSlug(value string) string {
	var out strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(value) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			out.WriteRune(r)
			lastDash = false
			continue
		}
		if out.Len() > 0 && !lastDash {
			out.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(out.String(), "-")
}
